FROM scratch AS ctx
COPY build_files /

/*
# Here are more base images:
# Universal Blue Images: https://github.com/orgs/ublue-os/packages
# Fedora base image: quay.io/fedora/fedora-bootc:41
# CentOS base images: quay.io/centos-bootc/centos-bootc:stream10
*/

#if defined workstation
#define TAG "workstation"
FROM ghcr.io/ublue-os/bluefin-dx:gts

#elif defined silverblue
#define TAG "silverblue"
FROM ghcr.io/ublue-os/silverblue-main:latest

#else
#define TAG "latest"
FROM ghcr.io/ublue-os/bluefin-dx:gts
#endif

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh TAG && \
    ostree container commit

/*
# Verify final image and contents are correct.
*/
RUN bootc container lint
