---
name: Build latest container image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build_image:
    uses: ./.github/reusable/build-image.yml
    secrets: inherit
    with:
      image_flavor: latest
